In [1]:
!pip install joblib
import os 
import matplotlib.pyplot as plt 
import joblib
import numpy as np

In [4]:
plt.style.use("fivethirtyeight")
import pandas as pd

In [ ]:
-np.ones((4,1))

In [ ]:
X = np.ones((4,2))
X

In [ ]:
np.c_[X, -np.ones((4,1)

In [ ]:
# eta is learning rate and epochs is no of iterations/ always recommend to keep the weights small

In [37]:
class Perceptron:
    def __init__(self, eta:float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4 #always recommend to keep the weights small
        self.eta = eta #learning rate
        self.epochs = epochs # iterations
        
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
    
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for each >> {epoch + 1}")
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights +self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
                  
                  
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
        

In [38]:
OR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [39]:
 def prepare_data(df, target_col="y"):
        X = df.drop(target_col, axis = 1)
        y = df[target_col]
        
        return X,y

In [40]:
X,y = prepare_data(df_OR)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [41]:
ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)
model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for each >> 1
predicted value after forward pass: 
[0 0 1 1]
error: 
0    0
1    1
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.00012211  0.0999943  -0.09995497]
####################
--------------------
for each >> 2
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[1.22112038e-04 9.99942970e-02 4.50312182e-05]
####################
--------------------
for each >> 3
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[1.22112038e-04 9.99942970e-02 4.50312182e-05]
####################
--------------------
for each >> 4
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: 
[1.22112038e-04 9.99942970

In [43]:
model_or.predict(X)

array([0, 1, 1, 1])

In [44]:
model_or.predict(X=[[1,1]])

array([1])

In [13]:
obj  = Perceptron(eta=0.01, epochs=10)

In [14]:
obj.eta

0.01

In [15]:
obj.weights

array([-5.11293742e-05, -6.94820418e-05, -5.74328843e-05])

In [16]:
obj.epochs

10

In [17]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [20]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])