In [1]:
!pip install joblib
import os 
import matplotlib.pyplot as plt 
import joblib
import numpy as np

In [2]:
plt.style.use("fivethirtyeight")

In [ ]:
-np.ones((4,1))

In [ ]:
X = np.ones((4,2))
X

In [ ]:
np.c_[X, -np.ones((4,1)

In [ ]:
# eta is learning rate and epochs is no of iterations/ always recommend to keep the weights small

In [12]:
class Perceptron:
    def __init__(self, eta:float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4 #always recommend to keep the weights small
        self.eta = eta #learning rate
        self.epochs = epochs # iterations
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        

In [13]:
obj  = Perceptron(eta=0.01, epochs=10)

In [14]:
obj.eta

0.01

In [15]:
obj.weights

array([-5.11293742e-05, -6.94820418e-05, -5.74328843e-05])

In [16]:
obj.epochs

10

In [17]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [20]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])